### ISSUE TITLE
Define hierarchical structure of classes

### ISSUE THREAD

**Issue by tfonrouge** [tfonrouge/HBTui#1]

**Comment by tfonrouge** [comment]
Hi Rafal, we need to define the structure of classes.
Seems that you have chosen a structure based on the Qt model, It's ok.
But we need to define (for the moment) a sub-set of such model, because Qt number of classes are
very, very huge.

For example, we can define the required for the following simple controls:
- Menu's
- Text Editor
- Choose List
- Browse
- Button
- ...

**Comment by ghost** [comment]
Hi Teo, well built beginning.

**Comment by tfonrouge** [comment]
Okay, let's start with the current classes that you defined in the Wiki :)

**Comment by tfonrouge** [comment]
Hey Rafal,
We need to define which properties/messages we'll use on our HBTui classes.
Let's start with the HBTui_Object class, what do you think ?

**Comment by ghost** [comment]
I think it's a good idea to select HBTui_Object class

**Comment by ghost** [comment]
Teo, We must lead ChangeLog
I'm staying behind in :)
